# coding: utf-8

"""
    Pupil Cloud

    Pupil Cloud API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.template_item import TemplateItem

class TestTemplateItem(unittest.TestCase):
    """TemplateItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TemplateItem:
        """Test TemplateItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TemplateItem`
        """
        model = TemplateItem()
        if include_optional:
            return TemplateItem(
                choices = [
                    ''
                    ],
                help_text = '',
                id = '00000000-0000-0000-0000-000000000000',
                input_type = 'any',
                required = True,
                title = '',
                widget_type = 'TEXT'
            )
        else:
            return TemplateItem(
                widget_type = 'TEXT',
        )
        """

    def testTemplateItem(self):
        """Test TemplateItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
