# coding: utf-8

"""
    Pupil Cloud

    Pupil Cloud API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.templates_api import TemplatesApi


class TestTemplatesApi(unittest.TestCase):
    """TemplatesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TemplatesApi()

    def tearDown(self) -> None:
        pass

    def test_delete_template(self) -> None:
        """Test case for delete_template

        Delete a template
        """
        pass

    def test_delete_templates(self) -> None:
        """Test case for delete_templates

        Delete multiple templates
        """
        pass

    def test_get_template(self) -> None:
        """Test case for get_template

        Returns a template with {template_id}
        """
        pass

    def test_get_templates(self) -> None:
        """Test case for get_templates

        List all templates
        """
        pass

    def test_patch_template(self) -> None:
        """Test case for patch_template

        Update a template
        """
        pass

    def test_post_template(self) -> None:
        """Test case for post_template

        Create a new template
        """
        pass


if __name__ == '__main__':
    unittest.main()
