# coding: utf-8

"""
    Pupil Cloud

    Pupil Cloud API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.markerless_gaze_on_aoi_get_response import MarkerlessGazeOnAoiGetResponse

class TestMarkerlessGazeOnAoiGetResponse(unittest.TestCase):
    """MarkerlessGazeOnAoiGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MarkerlessGazeOnAoiGetResponse:
        """Test MarkerlessGazeOnAoiGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MarkerlessGazeOnAoiGetResponse`
        """
        model = MarkerlessGazeOnAoiGetResponse()
        if include_optional:
            return MarkerlessGazeOnAoiGetResponse(
                code = 200.0,
                result = [
                    openapi_client.models.gaze_on_aoi.GazeOnAoi(
                        end_timestamp = 1.337, 
                        fixation_id = 56, 
                        gaze_in_aoi_x = 1.337, 
                        gaze_in_aoi_y = 1.337, 
                        start_timestamp = 1.337, )
                    ],
                status = 'success'
            )
        else:
            return MarkerlessGazeOnAoiGetResponse(
        )
        """

    def testMarkerlessGazeOnAoiGetResponse(self):
        """Test MarkerlessGazeOnAoiGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
