# coding: utf-8

"""
    Pupil Cloud

    Pupil Cloud API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.surface_post_response import SurfacePostResponse

class TestSurfacePostResponse(unittest.TestCase):
    """SurfacePostResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SurfacePostResponse:
        """Test SurfacePostResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SurfacePostResponse`
        """
        model = SurfacePostResponse()
        if include_optional:
            return SurfacePostResponse(
                code = 200.0,
                result = openapi_client.models.surface.Surface(
                    id = '00000000-0000-0000-0000-000000000000', 
                    is_initialized = True, 
                    markers_used = [
                        ''
                        ], 
                    name = '', ),
                status = 'success'
            )
        else:
            return SurfacePostResponse(
        )
        """

    def testSurfacePostResponse(self):
        """Test SurfacePostResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
