# coding: utf-8

"""
    Pupil Cloud

    Pupil Cloud API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.markerless_api import MarkerlessApi


class TestMarkerlessApi(unittest.TestCase):
    """MarkerlessApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MarkerlessApi()

    def tearDown(self) -> None:
        pass

    def test_get_markerless(self) -> None:
        """Test case for get_markerless

        Get markerless definition
        """
        pass

    def test_get_markerless_camera_poses(self) -> None:
        """Test case for get_markerless_camera_poses

        get markerless camera poses
        """
        pass

    def test_get_markerless_detections_timeline(self) -> None:
        """Test case for get_markerless_detections_timeline

        Recording markerless detections
        """
        pass

    def test_get_markerless_gaze_on_aoi(self) -> None:
        """Test case for get_markerless_gaze_on_aoi

        get gaze on aoi data for markerless enrichment
        """
        pass

    def test_get_markerless_point_cloud(self) -> None:
        """Test case for get_markerless_point_cloud

        """
        pass

    def test_initialize_markerless(self) -> None:
        """Test case for initialize_markerless

        Create markerless definition
        """
        pass

    def test_scan_markerless(self) -> None:
        """Test case for scan_markerless

        Scan markerless
        """
        pass


if __name__ == '__main__':
    unittest.main()
