# coding: utf-8

"""
    Pupil Cloud

    Pupil Cloud API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.recording_blinks_get_response import RecordingBlinksGetResponse

class TestRecordingBlinksGetResponse(unittest.TestCase):
    """RecordingBlinksGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RecordingBlinksGetResponse:
        """Test RecordingBlinksGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RecordingBlinksGetResponse`
        """
        model = RecordingBlinksGetResponse()
        if include_optional:
            return RecordingBlinksGetResponse(
                code = 200.0,
                result = [
                    openapi_client.models.blinks.Blinks(
                        id = 56, 
                        start = 1.337, 
                        stop = 1.337, )
                    ],
                status = 'success'
            )
        else:
            return RecordingBlinksGetResponse(
        )
        """

    def testRecordingBlinksGetResponse(self):
        """Test RecordingBlinksGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
