# coding: utf-8

"""
    Pupil Cloud

    Pupil Cloud API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.surface_corners_get_response import SurfaceCornersGetResponse

class TestSurfaceCornersGetResponse(unittest.TestCase):
    """SurfaceCornersGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SurfaceCornersGetResponse:
        """Test SurfaceCornersGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SurfaceCornersGetResponse`
        """
        model = SurfaceCornersGetResponse()
        if include_optional:
            return SurfaceCornersGetResponse(
                code = 200.0,
                result = [
                    openapi_client.models.surface_result.SurfaceResult(
                        corners = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        end_timestamp = 1.337, 
                        marker_ids = [
                            ''
                            ], 
                        start_timestamp = 1.337, )
                    ],
                status = 'success'
            )
        else:
            return SurfaceCornersGetResponse(
        )
        """

    def testSurfaceCornersGetResponse(self):
        """Test SurfaceCornersGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
