# coding: utf-8

"""
    Pupil Cloud

    Pupil Cloud API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.world_render_api import WorldRenderApi


class TestWorldRenderApi(unittest.TestCase):
    """WorldRenderApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WorldRenderApi()

    def tearDown(self) -> None:
        pass

    def test_get_render(self) -> None:
        """Test case for get_render

        Get a render enrichment
        """
        pass

    def test_initialize_rendering(self) -> None:
        """Test case for initialize_rendering

        Create world render definition
        """
        pass

    def test_patch_render(self) -> None:
        """Test case for patch_render

        Update a render enrichment
        """
        pass


if __name__ == '__main__':
    unittest.main()
