# coding: utf-8

"""
    Pupil Cloud

    Pupil Cloud API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.aoi_api import AoiApi


class TestAoiApi(unittest.TestCase):
    """AoiApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AoiApi()

    def tearDown(self) -> None:
        pass

    def test_delete_aoi(self) -> None:
        """Test case for delete_aoi

        Delete an aoi
        """
        pass

    def test_delete_aois(self) -> None:
        """Test case for delete_aois

        Delete multiple aois
        """
        pass

    def test_delete_aois_0(self) -> None:
        """Test case for delete_aois_0

        Delete multiple aois
        """
        pass

    def test_get_aoi(self) -> None:
        """Test case for get_aoi

        Returns an aoi with {aoi_id}
        """
        pass

    def test_get_aoi_stats(self) -> None:
        """Test case for get_aoi_stats

        List all aois of an enrichment
        """
        pass

    def test_get_aois(self) -> None:
        """Test case for get_aois

        List all aois of an enrichment
        """
        pass

    def test_patch_aoi(self) -> None:
        """Test case for patch_aoi

        Update an aoi
        """
        pass

    def test_post_aoi(self) -> None:
        """Test case for post_aoi

        Create a new aoi
        """
        pass

    def test_post_aoi_0(self) -> None:
        """Test case for post_aoi_0

        Create a new aoi
        """
        pass

    def test_post_aoi_1(self) -> None:
        """Test case for post_aoi_1

        Create a new aoi
        """
        pass


if __name__ == '__main__':
    unittest.main()
