# coding: utf-8

"""
    Pupil Cloud

    Pupil Cloud API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.wearers_api import WearersApi


class TestWearersApi(unittest.TestCase):
    """WearersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WearersApi()

    def tearDown(self) -> None:
        pass

    def test_delete_wearer(self) -> None:
        """Test case for delete_wearer

        Delete a wearer
        """
        pass

    def test_delete_wearers(self) -> None:
        """Test case for delete_wearers

        Delete multiple wearers
        """
        pass

    def test_get_wearer(self) -> None:
        """Test case for get_wearer

        Returns a wearer with {wearer_id}
        """
        pass

    def test_get_wearers(self) -> None:
        """Test case for get_wearers

        List all wearers
        """
        pass

    def test_patch_wearer(self) -> None:
        """Test case for patch_wearer

        Update a wearer
        """
        pass

    def test_post_wearer(self) -> None:
        """Test case for post_wearer

        Create a new wearer
        """
        pass


if __name__ == '__main__':
    unittest.main()
