# coding: utf-8

"""
    Pupil Cloud

    Pupil Cloud API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.surface_patch_response import SurfacePatchResponse

class TestSurfacePatchResponse(unittest.TestCase):
    """SurfacePatchResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SurfacePatchResponse:
        """Test SurfacePatchResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SurfacePatchResponse`
        """
        model = SurfacePatchResponse()
        if include_optional:
            return SurfacePatchResponse(
                code = 200.0,
                result = openapi_client.models.surface.Surface(
                    id = '00000000-0000-0000-0000-000000000000', 
                    is_initialized = True, 
                    markers_used = [
                        ''
                        ], 
                    name = '', ),
                status = 'success'
            )
        else:
            return SurfacePatchResponse(
        )
        """

    def testSurfacePatchResponse(self):
        """Test SurfacePatchResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
