# coding: utf-8

"""
    Pupil Cloud

    Pupil Cloud API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.recording_event_post_response import RecordingEventPostResponse

class TestRecordingEventPostResponse(unittest.TestCase):
    """RecordingEventPostResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RecordingEventPostResponse:
        """Test RecordingEventPostResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RecordingEventPostResponse`
        """
        model = RecordingEventPostResponse()
        if include_optional:
            return RecordingEventPostResponse(
                code = 200.0,
                result = openapi_client.models.recording_event.RecordingEvent(
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    created_by_user_id = '00000000-0000-0000-0000-000000000000', 
                    epoch_ns = 56, 
                    id = '00000000-0000-0000-0000-000000000000', 
                    name = '', 
                    offset_s = 1.337, 
                    origin = 'recording', 
                    recording_id = '00000000-0000-0000-0000-000000000000', 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                status = 'success'
            )
        else:
            return RecordingEventPostResponse(
        )
        """

    def testRecordingEventPostResponse(self):
        """Test RecordingEventPostResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
