# coding: utf-8

"""
    Pupil Cloud

    Pupil Cloud API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.camera_pose import CameraPose

class TestCameraPose(unittest.TestCase):
    """CameraPose unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CameraPose:
        """Test CameraPose
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CameraPose`
        """
        model = CameraPose()
        if include_optional:
            return CameraPose(
                end_timestamp = 1.337,
                rotation_x = 1.337,
                rotation_y = 1.337,
                rotation_z = 1.337,
                start_timestamp = 1.337,
                translation_x = 1.337,
                translation_y = 1.337,
                translation_z = 1.337
            )
        else:
            return CameraPose(
        )
        """

    def testCameraPose(self):
        """Test CameraPose"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
