# coding: utf-8

"""
    Pupil Cloud

    Pupil Cloud API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.workspace_get_response import WorkspaceGetResponse

class TestWorkspaceGetResponse(unittest.TestCase):
    """WorkspaceGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkspaceGetResponse:
        """Test WorkspaceGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkspaceGetResponse`
        """
        model = WorkspaceGetResponse()
        if include_optional:
            return WorkspaceGetResponse(
                code = 200.0,
                result = openapi_client.models.workspace_response.WorkspaceResponse(
                    alpha_features = True, 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    created_by_user_id = '00000000-0000-0000-0000-000000000000', 
                    default_template_id = '', 
                    deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deleted_by_user_id = '00000000-0000-0000-0000-000000000000', 
                    id = '00000000-0000-0000-0000-000000000000', 
                    name = '', 
                    picture_url = '', 
                    plan_id = '', 
                    raw_file_downloads = True, 
                    status = '', 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    world_video_mode = 'NORMAL', ),
                status = 'success'
            )
        else:
            return WorkspaceGetResponse(
        )
        """

    def testWorkspaceGetResponse(self):
        """Test WorkspaceGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
