# coding: utf-8

"""
    Pupil Cloud

    Pupil Cloud API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.filters_api import FiltersApi


class TestFiltersApi(unittest.TestCase):
    """FiltersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FiltersApi()

    def tearDown(self) -> None:
        pass

    def test_delete_filter(self) -> None:
        """Test case for delete_filter

        Delete a filter
        """
        pass

    def test_delete_filters(self) -> None:
        """Test case for delete_filters

        Delete multiple filters
        """
        pass

    def test_get_filter(self) -> None:
        """Test case for get_filter

        Returns a filter with {filter_id}
        """
        pass

    def test_get_filters(self) -> None:
        """Test case for get_filters

        List all filters
        """
        pass

    def test_patch_filter(self) -> None:
        """Test case for patch_filter

        Update a filter
        """
        pass

    def test_post_filters(self) -> None:
        """Test case for post_filters

        Create a new filter
        """
        pass


if __name__ == '__main__':
    unittest.main()
