# coding: utf-8

"""
    Pupil Cloud

    Pupil Cloud API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.point_cloud import PointCloud

class TestPointCloud(unittest.TestCase):
    """PointCloud unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PointCloud:
        """Test PointCloud
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PointCloud`
        """
        model = PointCloud()
        if include_optional:
            return PointCloud(
                id = '00000000-0000-0000-0000-000000000000',
                x = 1.337,
                y = 1.337,
                z = 1.337
            )
        else:
            return PointCloud(
        )
        """

    def testPointCloud(self):
        """Test PointCloud"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
