# coding: utf-8

"""
    Pupil Cloud

    Pupil Cloud API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.recording_fixations_get_response import RecordingFixationsGetResponse

class TestRecordingFixationsGetResponse(unittest.TestCase):
    """RecordingFixationsGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RecordingFixationsGetResponse:
        """Test RecordingFixationsGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RecordingFixationsGetResponse`
        """
        model = RecordingFixationsGetResponse()
        if include_optional:
            return RecordingFixationsGetResponse(
                code = 200.0,
                result = [
                    openapi_client.models.fixations.Fixations(
                        id = 56, 
                        start = 1.337, 
                        stop = 1.337, )
                    ],
                status = 'success'
            )
        else:
            return RecordingFixationsGetResponse(
        )
        """

    def testRecordingFixationsGetResponse(self):
        """Test RecordingFixationsGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
