# coding: utf-8

"""
    Pupil Cloud

    Pupil Cloud API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.project_enrichment_post_response import ProjectEnrichmentPostResponse

class TestProjectEnrichmentPostResponse(unittest.TestCase):
    """ProjectEnrichmentPostResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectEnrichmentPostResponse:
        """Test ProjectEnrichmentPostResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectEnrichmentPostResponse`
        """
        model = ProjectEnrichmentPostResponse()
        if include_optional:
            return ProjectEnrichmentPostResponse(
                code = 200.0,
                result = openapi_client.models.project_enrichment.ProjectEnrichment(
                    created_by_user_id = '00000000-0000-0000-0000-000000000000', 
                    deleted_by_user_id = '00000000-0000-0000-0000-000000000000', 
                    enrichment_id = '00000000-0000-0000-0000-000000000000', 
                    fps = 56, 
                    project_id = '00000000-0000-0000-0000-000000000000', ),
                status = 'success'
            )
        else:
            return ProjectEnrichmentPostResponse(
        )
        """

    def testProjectEnrichmentPostResponse(self):
        """Test ProjectEnrichmentPostResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
