# coding: utf-8

"""
    Pupil Cloud

    Pupil Cloud API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.hardware_api import HardwareApi


class TestHardwareApi(unittest.TestCase):
    """HardwareApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HardwareApi()

    def tearDown(self) -> None:
        pass

    def test_get_hardware(self) -> None:
        """Test case for get_hardware

        Returns calibration
        """
        pass


if __name__ == '__main__':
    unittest.main()
