# coding: utf-8

"""
    Pupil Cloud

    Pupil Cloud API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.markerless_detections_timeline_get_response import MarkerlessDetectionsTimelineGetResponse

class TestMarkerlessDetectionsTimelineGetResponse(unittest.TestCase):
    """MarkerlessDetectionsTimelineGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MarkerlessDetectionsTimelineGetResponse:
        """Test MarkerlessDetectionsTimelineGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MarkerlessDetectionsTimelineGetResponse`
        """
        model = MarkerlessDetectionsTimelineGetResponse()
        if include_optional:
            return MarkerlessDetectionsTimelineGetResponse(
                code = 200.0,
                result = [
                    openapi_client.models.markerless_timeline.MarkerlessTimeline(
                        aoi_detected = 1.337, 
                        avg_gaze_on_aoi = 1.337, 
                        end_timestamp = 1.337, 
                        gaze_on_aoi = 1.337, 
                        start_timestamp = 1.337, 
                        sum_gaze_on_aoi = 56, 
                        total_frames = 56, )
                    ],
                status = 'success'
            )
        else:
            return MarkerlessDetectionsTimelineGetResponse(
        )
        """

    def testMarkerlessDetectionsTimelineGetResponse(self):
        """Test MarkerlessDetectionsTimelineGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
