# coding: utf-8

"""
    Pupil Cloud

    Pupil Cloud API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.surface_initialization import SurfaceInitialization

class TestSurfaceInitialization(unittest.TestCase):
    """SurfaceInitialization unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SurfaceInitialization:
        """Test SurfaceInitialization
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SurfaceInitialization`
        """
        model = SurfaceInitialization()
        if include_optional:
            return SurfaceInitialization(
                name = ''
            )
        else:
            return SurfaceInitialization(
                name = '',
        )
        """

    def testSurfaceInitialization(self):
        """Test SurfaceInitialization"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
