# coding: utf-8

"""
    Pupil Cloud

    Pupil Cloud API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.recording_scene_camera_intrinsics_get_response import RecordingSceneCameraIntrinsicsGetResponse

class TestRecordingSceneCameraIntrinsicsGetResponse(unittest.TestCase):
    """RecordingSceneCameraIntrinsicsGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RecordingSceneCameraIntrinsicsGetResponse:
        """Test RecordingSceneCameraIntrinsicsGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RecordingSceneCameraIntrinsicsGetResponse`
        """
        model = RecordingSceneCameraIntrinsicsGetResponse()
        if include_optional:
            return RecordingSceneCameraIntrinsicsGetResponse(
                code = 200.0,
                result = openapi_client.models.scene_camera_intrinsics.SceneCameraIntrinsics(
                    camera_matrix = [
                        [
                            1.337
                            ]
                        ], 
                    dist_coefs = [
                        [
                            1.337
                            ]
                        ], 
                    rotation_matrix = [
                        [
                            1.337
                            ]
                        ], 
                    serial_number = '', 
                    version = '', ),
                status = 'success'
            )
        else:
            return RecordingSceneCameraIntrinsicsGetResponse(
        )
        """

    def testRecordingSceneCameraIntrinsicsGetResponse(self):
        """Test RecordingSceneCameraIntrinsicsGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
