# coding: utf-8

"""
    Pupil Cloud

    Pupil Cloud API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.project_recordings_resource_get_response import ProjectRecordingsResourceGetResponse

class TestProjectRecordingsResourceGetResponse(unittest.TestCase):
    """ProjectRecordingsResourceGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectRecordingsResourceGetResponse:
        """Test ProjectRecordingsResourceGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectRecordingsResourceGetResponse`
        """
        model = ProjectRecordingsResourceGetResponse()
        if include_optional:
            return ProjectRecordingsResourceGetResponse(
                code = 200.0,
                result = [
                    openapi_client.models.project_recording.ProjectRecording(
                        events = [
                            openapi_client.models.project_event.ProjectEvent(
                                count = 56, 
                                name = '', )
                            ], 
                        project_id = '00000000-0000-0000-0000-000000000000', 
                        recording_id = '00000000-0000-0000-0000-000000000000', )
                    ],
                status = 'success'
            )
        else:
            return ProjectRecordingsResourceGetResponse(
        )
        """

    def testProjectRecordingsResourceGetResponse(self):
        """Test ProjectRecordingsResourceGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
