# coding: utf-8

"""
    Pupil Cloud

    Pupil Cloud API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.face_detection_timeline import FaceDetectionTimeline

class TestFaceDetectionTimeline(unittest.TestCase):
    """FaceDetectionTimeline unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FaceDetectionTimeline:
        """Test FaceDetectionTimeline
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FaceDetectionTimeline`
        """
        model = FaceDetectionTimeline()
        if include_optional:
            return FaceDetectionTimeline(
                avg_faces = 1.337,
                end_timestamp = 1.337,
                max_faces = 56,
                min_faces = 56,
                start_timestamp = 1.337,
                total_frames = 56
            )
        else:
            return FaceDetectionTimeline(
        )
        """

    def testFaceDetectionTimeline(self):
        """Test FaceDetectionTimeline"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
