# coding: utf-8

"""
    Pupil Cloud

    Pupil Cloud API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.gaze_circle import GazeCircle

class TestGazeCircle(unittest.TestCase):
    """GazeCircle unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GazeCircle:
        """Test GazeCircle
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GazeCircle`
        """
        model = GazeCircle()
        if include_optional:
            return GazeCircle(
                color = openapi_client.models.color.Color(
                    alpha = 0, 
                    blue = 0, 
                    green = 0, 
                    red = 0, ),
                radius = 56,
                stroke_width = 56
            )
        else:
            return GazeCircle(
        )
        """

    def testGazeCircle(self):
        """Test GazeCircle"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
