# coding: utf-8

"""
    Pupil Cloud

    Pupil Cloud API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.recording_event_create_response import RecordingEventCreateResponse

class TestRecordingEventCreateResponse(unittest.TestCase):
    """RecordingEventCreateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RecordingEventCreateResponse:
        """Test RecordingEventCreateResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RecordingEventCreateResponse`
        """
        model = RecordingEventCreateResponse()
        if include_optional:
            return RecordingEventCreateResponse(
                code = 200.0,
                result = openapi_client.models.create_recording_event.CreateRecordingEvent(
                    name = '', 
                    offset_s = 1.337, ),
                status = 'success'
            )
        else:
            return RecordingEventCreateResponse(
        )
        """

    def testRecordingEventCreateResponse(self):
        """Test RecordingEventCreateResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
