# coding: utf-8

"""
    Pupil Cloud

    Pupil Cloud API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.visualization_config_post_response import VisualizationConfigPostResponse

class TestVisualizationConfigPostResponse(unittest.TestCase):
    """VisualizationConfigPostResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VisualizationConfigPostResponse:
        """Test VisualizationConfigPostResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VisualizationConfigPostResponse`
        """
        model = VisualizationConfigPostResponse()
        if include_optional:
            return VisualizationConfigPostResponse(
                code = 200.0,
                result = openapi_client.models.visualization_config.VisualizationConfig(
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    enrichment_id = '00000000-0000-0000-0000-000000000000', 
                    id = '00000000-0000-0000-0000-000000000000', 
                    kind = 'heatmap', 
                    name = '', 
                    payload = {
                        'key' : None
                        }, 
                    project_id = '00000000-0000-0000-0000-000000000000', 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                status = 'success'
            )
        else:
            return VisualizationConfigPostResponse(
        )
        """

    def testVisualizationConfigPostResponse(self):
        """Test VisualizationConfigPostResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
