# coding: utf-8

"""
    Pupil Cloud

    Pupil Cloud API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.login_post_response import LoginPostResponse

class TestLoginPostResponse(unittest.TestCase):
    """LoginPostResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LoginPostResponse:
        """Test LoginPostResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LoginPostResponse`
        """
        model = LoginPostResponse()
        if include_optional:
            return LoginPostResponse(
                code = 200.0,
                result = openapi_client.models.profile.Profile(
                    default_workspace_id = '00000000-0000-0000-0000-000000000000', 
                    email = '', 
                    email_verified = True, 
                    id = '', 
                    name = '', 
                    onboarded_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    photo_url = '', 
                    product_updates_subscribed = True, 
                    provider = '', 
                    uid = '', 
                    user_workspaces = [
                        None
                        ], ),
                status = 'success'
            )
        else:
            return LoginPostResponse(
        )
        """

    def testLoginPostResponse(self):
        """Test LoginPostResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
