# coding: utf-8

"""
    Pupil Cloud

    Pupil Cloud API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.recording_event_patch_request import RecordingEventPatchRequest

class TestRecordingEventPatchRequest(unittest.TestCase):
    """RecordingEventPatchRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RecordingEventPatchRequest:
        """Test RecordingEventPatchRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RecordingEventPatchRequest`
        """
        model = RecordingEventPatchRequest()
        if include_optional:
            return RecordingEventPatchRequest(
                name = '',
                offset_s = 1.337
            )
        else:
            return RecordingEventPatchRequest(
        )
        """

    def testRecordingEventPatchRequest(self):
        """Test RecordingEventPatchRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
