# coding: utf-8

"""
    Pupil Cloud

    Pupil Cloud API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.apriltag_detections_get_response import ApriltagDetectionsGetResponse

class TestApriltagDetectionsGetResponse(unittest.TestCase):
    """ApriltagDetectionsGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApriltagDetectionsGetResponse:
        """Test ApriltagDetectionsGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApriltagDetectionsGetResponse`
        """
        model = ApriltagDetectionsGetResponse()
        if include_optional:
            return ApriltagDetectionsGetResponse(
                code = 200.0,
                result = [
                    openapi_client.models.apriltag_result.ApriltagResult(
                        distorted_apriltags = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        end_timestamp = 1.337, 
                        normalized_apriltags = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        start_timestamp = 1.337, )
                    ],
                status = 'success'
            )
        else:
            return ApriltagDetectionsGetResponse(
        )
        """

    def testApriltagDetectionsGetResponse(self):
        """Test ApriltagDetectionsGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
