# coding: utf-8

"""
    Pupil Cloud

    Pupil Cloud API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.workspaces_api import WorkspacesApi


class TestWorkspacesApi(unittest.TestCase):
    """WorkspacesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WorkspacesApi()

    def tearDown(self) -> None:
        pass

    def test_create_workspace_invitation(self) -> None:
        """Test case for create_workspace_invitation

        Create a workspace invitation
        """
        pass

    def test_delete_workspace(self) -> None:
        """Test case for delete_workspace

        Delete a workspace
        """
        pass

    def test_delete_workspace_invitation(self) -> None:
        """Test case for delete_workspace_invitation

        Delete a workspace invitation
        """
        pass

    def test_delete_workspace_member(self) -> None:
        """Test case for delete_workspace_member

        Delete a workspace member from a workspace
        """
        pass

    def test_get_workspace(self) -> None:
        """Test case for get_workspace

        Returns the workspace with {workspace_id}
        """
        pass

    def test_get_workspace_invitation(self) -> None:
        """Test case for get_workspace_invitation

        Get workspace invitation for token
        """
        pass

    def test_get_workspace_member(self) -> None:
        """Test case for get_workspace_member

        Get workspace member
        """
        pass

    def test_get_workspace_members(self) -> None:
        """Test case for get_workspace_members

        List all members of workspace {workspace_id}
        """
        pass

    def test_get_workspaces(self) -> None:
        """Test case for get_workspaces

        List all workspaces for a user
        """
        pass

    def test_list_workspace_invitations(self) -> None:
        """Test case for list_workspace_invitations

        List workspace invitations
        """
        pass

    def test_patch_workspace_member(self) -> None:
        """Test case for patch_workspace_member

        Patch members of workspace {workspace_id}
        """
        pass

    def test_post_workspace(self) -> None:
        """Test case for post_workspace

        Create a new workspace
        """
        pass

    def test_post_workspace_members_resource(self) -> None:
        """Test case for post_workspace_members_resource

        Add workspace member
        """
        pass

    def test_update_workspace(self) -> None:
        """Test case for update_workspace

        Update a workspace
        """
        pass


if __name__ == '__main__':
    unittest.main()
