# coding: utf-8

"""
    Pupil Cloud

    Pupil Cloud API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.recording_blinks_timeline_get_response import RecordingBlinksTimelineGetResponse

class TestRecordingBlinksTimelineGetResponse(unittest.TestCase):
    """RecordingBlinksTimelineGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RecordingBlinksTimelineGetResponse:
        """Test RecordingBlinksTimelineGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RecordingBlinksTimelineGetResponse`
        """
        model = RecordingBlinksTimelineGetResponse()
        if include_optional:
            return RecordingBlinksTimelineGetResponse(
                code = 200.0,
                result = [
                    openapi_client.models.blinks_timeline.BlinksTimeline(
                        end_timestamp = 1.337, 
                        has_blinks = 56, 
                        max_blink_id = 56, 
                        min_blink_id = 56, 
                        start_timestamp = 1.337, 
                        total_blinks_count = 56, 
                        total_frames = 56, 
                        unique_blinks_count = 56, )
                    ],
                status = 'success'
            )
        else:
            return RecordingBlinksTimelineGetResponse(
        )
        """

    def testRecordingBlinksTimelineGetResponse(self):
        """Test RecordingBlinksTimelineGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
