# coding: utf-8

"""
    Pupil Cloud

    Pupil Cloud API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.aoi_patch_request import AoiPatchRequest

class TestAoiPatchRequest(unittest.TestCase):
    """AoiPatchRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AoiPatchRequest:
        """Test AoiPatchRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AoiPatchRequest`
        """
        model = AoiPatchRequest()
        if include_optional:
            return AoiPatchRequest(
                bounding_box = '',
                centroid_xy = '',
                color = '',
                description = '',
                enrichment_id = '00000000-0000-0000-0000-000000000000',
                id = '00000000-0000-0000-0000-000000000000',
                mask_image_data_url = '',
                name = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return AoiPatchRequest(
                name = '',
        )
        """

    def testAoiPatchRequest(self):
        """Test AoiPatchRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
