# coding: utf-8

"""
    Pupil Cloud

    Pupil Cloud API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.workspace_invitations_list_response import WorkspaceInvitationsListResponse

class TestWorkspaceInvitationsListResponse(unittest.TestCase):
    """WorkspaceInvitationsListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkspaceInvitationsListResponse:
        """Test WorkspaceInvitationsListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkspaceInvitationsListResponse`
        """
        model = WorkspaceInvitationsListResponse()
        if include_optional:
            return WorkspaceInvitationsListResponse(
                code = 200.0,
                result = [
                    openapi_client.models.workspace_invitation.WorkspaceInvitation(
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_by_user_id = '00000000-0000-0000-0000-000000000000', 
                        email = '', 
                        expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        id = '00000000-0000-0000-0000-000000000000', 
                        role = 'VIEWER', 
                        token = '', 
                        workspace_id = '00000000-0000-0000-0000-000000000000', )
                    ],
                status = 'success'
            )
        else:
            return WorkspaceInvitationsListResponse(
        )
        """

    def testWorkspaceInvitationsListResponse(self):
        """Test WorkspaceInvitationsListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
