# coding: utf-8

"""
    Pupil Cloud

    Pupil Cloud API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.workspace_member_post_request import WorkspaceMemberPostRequest

class TestWorkspaceMemberPostRequest(unittest.TestCase):
    """WorkspaceMemberPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkspaceMemberPostRequest:
        """Test WorkspaceMemberPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkspaceMemberPostRequest`
        """
        model = WorkspaceMemberPostRequest()
        if include_optional:
            return WorkspaceMemberPostRequest(
                role = 'VIEWER',
                user_id = '00000000-0000-0000-0000-000000000000'
            )
        else:
            return WorkspaceMemberPostRequest(
                role = 'VIEWER',
        )
        """

    def testWorkspaceMemberPostRequest(self):
        """Test WorkspaceMemberPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
