# coding: utf-8

"""
    Pupil Cloud

    Pupil Cloud API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.heatmap_api import HeatmapApi


class TestHeatmapApi(unittest.TestCase):
    """HeatmapApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HeatmapApi()

    def tearDown(self) -> None:
        pass

    def test_get_download_heatmap(self) -> None:
        """Test case for get_download_heatmap

        download zip file with heatmaps
        """
        pass

    def test_get_heatmap(self) -> None:
        """Test case for get_heatmap

        get heatmap image or json data
        """
        pass

    def test_get_heatmap_background(self) -> None:
        """Test case for get_heatmap_background

        get heatmap background for overlay
        """
        pass

    def test_post_download_heatmap(self) -> None:
        """Test case for post_download_heatmap

        download zip file with heatmaps
        """
        pass

    def test_post_heatmap(self) -> None:
        """Test case for post_heatmap

        get heatmap image or json data
        """
        pass


if __name__ == '__main__':
    unittest.main()
