# coding: utf-8

"""
    Pupil Cloud

    Pupil Cloud API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.generate_heatmap import GenerateHeatmap

class TestGenerateHeatmap(unittest.TestCase):
    """GenerateHeatmap unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GenerateHeatmap:
        """Test GenerateHeatmap
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GenerateHeatmap`
        """
        model = GenerateHeatmap()
        if include_optional:
            return GenerateHeatmap(
                colormap = 'Turbo',
                enrichment_id = '00000000-0000-0000-0000-000000000000',
                height = 56,
                var_json = True,
                max_size = 56,
                n_bins = 56,
                project_id = '00000000-0000-0000-0000-000000000000',
                recording_ids = [
                    '00000000-0000-0000-0000-000000000000'
                    ],
                sigma = 1.337,
                width = 56
            )
        else:
            return GenerateHeatmap(
                enrichment_id = '00000000-0000-0000-0000-000000000000',
                project_id = '00000000-0000-0000-0000-000000000000',
        )
        """

    def testGenerateHeatmap(self):
        """Test GenerateHeatmap"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
