# coding: utf-8

"""
    Pupil Cloud

    Pupil Cloud API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.surface_gaze_on_aoi_get_response import SurfaceGazeOnAoiGetResponse

class TestSurfaceGazeOnAoiGetResponse(unittest.TestCase):
    """SurfaceGazeOnAoiGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SurfaceGazeOnAoiGetResponse:
        """Test SurfaceGazeOnAoiGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SurfaceGazeOnAoiGetResponse`
        """
        model = SurfaceGazeOnAoiGetResponse()
        if include_optional:
            return SurfaceGazeOnAoiGetResponse(
                code = 200.0,
                result = [
                    openapi_client.models.gaze_on_aoi.GazeOnAoi(
                        end_timestamp = 1.337, 
                        fixation_id = 56, 
                        gaze_in_aoi_x = 1.337, 
                        gaze_in_aoi_y = 1.337, 
                        start_timestamp = 1.337, )
                    ],
                status = 'success'
            )
        else:
            return SurfaceGazeOnAoiGetResponse(
        )
        """

    def testSurfaceGazeOnAoiGetResponse(self):
        """Test SurfaceGazeOnAoiGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
