# coding: utf-8

"""
    Pupil Cloud

    Pupil Cloud API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.recording_fixations_timeline_get_response import RecordingFixationsTimelineGetResponse

class TestRecordingFixationsTimelineGetResponse(unittest.TestCase):
    """RecordingFixationsTimelineGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RecordingFixationsTimelineGetResponse:
        """Test RecordingFixationsTimelineGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RecordingFixationsTimelineGetResponse`
        """
        model = RecordingFixationsTimelineGetResponse()
        if include_optional:
            return RecordingFixationsTimelineGetResponse(
                code = 200.0,
                result = [
                    openapi_client.models.fixations_timeline.FixationsTimeline(
                        end_timestamp = 1.337, 
                        has_fixations = 56, 
                        max_fixation_id = 56, 
                        min_fixation_id = 56, 
                        start_timestamp = 1.337, 
                        total_fixations_count = 56, 
                        total_frames = 56, 
                        unique_fixations_count = 56, )
                    ],
                status = 'success'
            )
        else:
            return RecordingFixationsTimelineGetResponse(
        )
        """

    def testRecordingFixationsTimelineGetResponse(self):
        """Test RecordingFixationsTimelineGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
