# coding: utf-8

"""
    Pupil Cloud

    Pupil Cloud API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.aois_delete_request import AoisDeleteRequest

class TestAoisDeleteRequest(unittest.TestCase):
    """AoisDeleteRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AoisDeleteRequest:
        """Test AoisDeleteRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AoisDeleteRequest`
        """
        model = AoisDeleteRequest()
        if include_optional:
            return AoisDeleteRequest(
                aoi_ids = [
                    '00000000-0000-0000-0000-000000000000'
                    ]
            )
        else:
            return AoisDeleteRequest(
        )
        """

    def testAoisDeleteRequest(self):
        """Test AoisDeleteRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
