# coding: utf-8

"""
    Pupil Cloud

    Pupil Cloud API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.face_detection import FaceDetection

class TestFaceDetection(unittest.TestCase):
    """FaceDetection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FaceDetection:
        """Test FaceDetection
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FaceDetection`
        """
        model = FaceDetection()
        if include_optional:
            return FaceDetection(
                end_timestamp = 1.337,
                faces = [
                    None
                    ],
                start_timestamp = 1.337
            )
        else:
            return FaceDetection(
        )
        """

    def testFaceDetection(self):
        """Test FaceDetection"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
