# coding: utf-8

"""
    Pupil Cloud

    Pupil Cloud API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.static_image_mapper_enrichments_get_response import StaticImageMapperEnrichmentsGetResponse

class TestStaticImageMapperEnrichmentsGetResponse(unittest.TestCase):
    """StaticImageMapperEnrichmentsGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StaticImageMapperEnrichmentsGetResponse:
        """Test StaticImageMapperEnrichmentsGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StaticImageMapperEnrichmentsGetResponse`
        """
        model = StaticImageMapperEnrichmentsGetResponse()
        if include_optional:
            return StaticImageMapperEnrichmentsGetResponse(
                code = 200.0,
                result = [
                    openapi_client.models.static_image_mapper_get_request.StaticImageMapperGetRequest(
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_by_user_id = '00000000-0000-0000-0000-000000000000', 
                        deleted_by_user_id = '00000000-0000-0000-0000-000000000000', 
                        error_message = '', 
                        fixations_status = [
                            None
                            ], 
                        from_event_name = '', 
                        id = '00000000-0000-0000-0000-000000000000', 
                        kind = 'marker-mapper', 
                        name = '', 
                        project_id = '00000000-0000-0000-0000-000000000000', 
                        slices = [
                            None
                            ], 
                        static_image_id = '00000000-0000-0000-0000-000000000000', 
                        static_image_image_thumbnail_url = '', 
                        status = None, 
                        to_event_name = '', 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                status = 'success'
            )
        else:
            return StaticImageMapperEnrichmentsGetResponse(
        )
        """

    def testStaticImageMapperEnrichmentsGetResponse(self):
        """Test StaticImageMapperEnrichmentsGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
