# coding: utf-8

"""
    Pupil Cloud

    Pupil Cloud API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.recording_gaze_get_response import RecordingGazeGetResponse

class TestRecordingGazeGetResponse(unittest.TestCase):
    """RecordingGazeGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RecordingGazeGetResponse:
        """Test RecordingGazeGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RecordingGazeGetResponse`
        """
        model = RecordingGazeGetResponse()
        if include_optional:
            return RecordingGazeGetResponse(
                code = 200.0,
                result = [
                    openapi_client.models.gaze_datapoint.GazeDatapoint(
                        blink_id = 56, 
                        end_timestamp = 1.337, 
                        fixation_id = 56, 
                        start_timestamp = 1.337, 
                        worn = 56, 
                        x = 56, 
                        y = 56, )
                    ],
                status = 'success'
            )
        else:
            return RecordingGazeGetResponse(
        )
        """

    def testRecordingGazeGetResponse(self):
        """Test RecordingGazeGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
