# coding: utf-8

"""
    Pupil Cloud

    Pupil Cloud API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.projects_api import ProjectsApi


class TestProjectsApi(unittest.TestCase):
    """ProjectsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProjectsApi()

    def tearDown(self) -> None:
        pass

    def test_clear_static_image_mapper_enrichments_recording_fixation(self) -> None:
        """Test case for clear_static_image_mapper_enrichments_recording_fixation

        Clear or resets all the mapped fixation of recording's
        """
        pass

    def test_delete_project_enrichment_resource(self) -> None:
        """Test case for delete_project_enrichment_resource

        Delete a project enrichment
        """
        pass

    def test_delete_project_recording_event_resource(self) -> None:
        """Test case for delete_project_recording_event_resource

        Delete a project recording event
        """
        pass

    def test_delete_project_resource(self) -> None:
        """Test case for delete_project_resource

        Delete a project
        """
        pass

    def test_delete_projects_resource(self) -> None:
        """Test case for delete_projects_resource

        Delete multiple projects
        """
        pass

    def test_delete_static_image_mapper_enrichments_recording_fixation(self) -> None:
        """Test case for delete_static_image_mapper_enrichments_recording_fixation

        Deletes coordinates of a particular fixation of recording's
        """
        pass

    def test_delete_visualization_config(self) -> None:
        """Test case for delete_visualization_config

        Delete a visualization config
        """
        pass

    def test_export_static_image_mapper_enrichment(self) -> None:
        """Test case for export_static_image_mapper_enrichment

        Export static image mapper enrichment
        """
        pass

    def test_get_project_enrichment(self) -> None:
        """Test case for get_project_enrichment

        Get a project enrichment
        """
        pass

    def test_get_project_enrichment_compute_resource(self) -> None:
        """Test case for get_project_enrichment_compute_resource

        """
        pass

    def test_get_project_enrichments(self) -> None:
        """Test case for get_project_enrichments

        List all project enrichments
        """
        pass

    def test_get_project_events_resource(self) -> None:
        """Test case for get_project_events_resource

        Returns a project's events with {project_id}
        """
        pass

    def test_get_project_recording_events_resource(self) -> None:
        """Test case for get_project_recording_events_resource

        Returns a project's recording event with {project_id} and {recording_id}
        """
        pass

    def test_get_project_recordings_resource(self) -> None:
        """Test case for get_project_recordings_resource

        Returns a project's recordings with {project_id}
        """
        pass

    def test_get_project_resource(self) -> None:
        """Test case for get_project_resource

        Returns a project with {project_id}
        """
        pass

    def test_get_project_unique_events(self) -> None:
        """Test case for get_project_unique_events

        Returns all unique events in a project
        """
        pass

    def test_get_projects_resource(self) -> None:
        """Test case for get_projects_resource

        List all projects
        """
        pass

    def test_get_static_image_mapper_enrichment(self) -> None:
        """Test case for get_static_image_mapper_enrichment

        Get a static image mapper enrichment
        """
        pass

    def test_get_static_image_mapper_enrichments(self) -> None:
        """Test case for get_static_image_mapper_enrichments

        List all static image mapper enrichments of a project
        """
        pass

    def test_get_static_image_mapper_enrichments_recording_fixations(self) -> None:
        """Test case for get_static_image_mapper_enrichments_recording_fixations

        List all the fixations of a recording's static image mapper enrichments
        """
        pass

    def test_get_visualization_config(self) -> None:
        """Test case for get_visualization_config

        Get a visualization config
        """
        pass

    def test_get_visualization_configs(self) -> None:
        """Test case for get_visualization_configs

        List project's visualization configs
        """
        pass

    def test_patch_project_enrichment_resource(self) -> None:
        """Test case for patch_project_enrichment_resource

        Update a project enrichment
        """
        pass

    def test_patch_project_recording_event_resource(self) -> None:
        """Test case for patch_project_recording_event_resource

        Update a project recording event
        """
        pass

    def test_patch_project_resource(self) -> None:
        """Test case for patch_project_resource

        Update a project
        """
        pass

    def test_patch_static_image_mapper_enrichment(self) -> None:
        """Test case for patch_static_image_mapper_enrichment

        Update a static image mapper enrichment
        """
        pass

    def test_patch_visualization_config(self) -> None:
        """Test case for patch_visualization_config

        Update a visualization config
        """
        pass

    def test_post_project_download_resource(self) -> None:
        """Test case for post_project_download_resource

        Download project data
        """
        pass

    def test_post_project_enrichment(self) -> None:
        """Test case for post_project_enrichment

        Create a new project enrichment
        """
        pass

    def test_post_project_enrichment_cancel_resource(self) -> None:
        """Test case for post_project_enrichment_cancel_resource

        """
        pass

    def test_post_project_enrichment_compute_resource(self) -> None:
        """Test case for post_project_enrichment_compute_resource

        """
        pass

    def test_post_project_enrichment_export_resource(self) -> None:
        """Test case for post_project_enrichment_export_resource

        Export an enrichment data
        """
        pass

    def test_post_project_recording_events_resource(self) -> None:
        """Test case for post_project_recording_events_resource

        Create a new project recording event
        """
        pass

    def test_post_projects_resource(self) -> None:
        """Test case for post_projects_resource

        Create a new project
        """
        pass

    def test_post_static_image_mapper_enrichment(self) -> None:
        """Test case for post_static_image_mapper_enrichment

        Create a new static image mapper enrichment
        """
        pass

    def test_post_visualization_config(self) -> None:
        """Test case for post_visualization_config

        Create a new visualization config
        """
        pass

    def test_project_enrichments_export(self) -> None:
        """Test case for project_enrichments_export

        Export an enrichment data
        """
        pass

    def test_put_static_image_mapper_enrichments_recording_fixation(self) -> None:
        """Test case for put_static_image_mapper_enrichments_recording_fixation

        Insert or update coordinates of a particular fixation of recording's
        """
        pass


if __name__ == '__main__':
    unittest.main()
