# coding: utf-8

"""
    Pupil Cloud

    Pupil Cloud API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class FilterPostRequest(BaseModel):
    """
    FilterPostRequest
    """ # noqa: E501
    created_at: Optional[datetime] = None
    filter_query: Optional[StrictStr] = None
    filter_scope: Optional[StrictStr] = Field(default=None, description="the scope of the filter")
    id: Optional[StrictStr] = None
    kind: Optional[StrictStr] = Field(default='lucene', description="the filter syntax kind")
    name: StrictStr
    updated_at: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["created_at", "filter_query", "filter_scope", "id", "kind", "name", "updated_at"]

    @field_validator('filter_scope')
    def filter_scope_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['recordings', 'templates', 'wearers']):
            raise ValueError("must be one of enum values ('recordings', 'templates', 'wearers')")
        return value

    @field_validator('kind')
    def kind_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['simple', 'lucene']):
            raise ValueError("must be one of enum values ('simple', 'lucene')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FilterPostRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FilterPostRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "created_at": obj.get("created_at"),
            "filter_query": obj.get("filter_query"),
            "filter_scope": obj.get("filter_scope"),
            "id": obj.get("id"),
            "kind": obj.get("kind") if obj.get("kind") is not None else 'lucene',
            "name": obj.get("name"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


