# coding: utf-8

"""
    Pupil Cloud

    Pupil Cloud API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class GenerateHeatmap(BaseModel):
    """
    GenerateHeatmap
    """ # noqa: E501
    colormap: Optional[StrictStr] = Field(default='Turbo', description="colormap for heatmap")
    enrichment_id: StrictStr
    height: Optional[StrictInt] = None
    var_json: Optional[StrictBool] = Field(default=False, alias="json")
    max_size: Optional[StrictInt] = None
    n_bins: Optional[StrictInt] = None
    project_id: StrictStr
    recording_ids: Optional[List[StrictStr]] = None
    sigma: Optional[Union[StrictFloat, StrictInt]] = None
    width: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["colormap", "enrichment_id", "height", "json", "max_size", "n_bins", "project_id", "recording_ids", "sigma", "width"]

    @field_validator('colormap')
    def colormap_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Turbo', 'Jet', 'Magma', 'Viridis', 'Traffic Light']):
            raise ValueError("must be one of enum values ('Turbo', 'Jet', 'Magma', 'Viridis', 'Traffic Light')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GenerateHeatmap from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GenerateHeatmap from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "colormap": obj.get("colormap") if obj.get("colormap") is not None else 'Turbo',
            "enrichment_id": obj.get("enrichment_id"),
            "height": obj.get("height"),
            "json": obj.get("json") if obj.get("json") is not None else False,
            "max_size": obj.get("max_size"),
            "n_bins": obj.get("n_bins"),
            "project_id": obj.get("project_id"),
            "recording_ids": obj.get("recording_ids"),
            "sigma": obj.get("sigma"),
            "width": obj.get("width")
        })
        return _obj


