# coding: utf-8

"""
    Pupil Cloud

    Pupil Cloud API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from pupilcloud.models.template_item import TemplateItem
from typing import Optional, Set
from typing_extensions import Self

class TemplatePatchRequest(BaseModel):
    """
    TemplatePatchRequest
    """ # noqa: E501
    archived_at: Optional[datetime] = None
    created_at: Optional[datetime] = None
    id: Optional[StrictStr] = None
    items: Optional[List[TemplateItem]] = None
    label_ids: Optional[List[StrictStr]] = None
    name: StrictStr
    published_at: Optional[datetime] = None
    recording_name_format: Optional[List[StrictStr]] = None
    updated_at: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["archived_at", "created_at", "id", "items", "label_ids", "name", "published_at", "recording_name_format", "updated_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TemplatePatchRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in items (list)
        _items = []
        if self.items:
            for _item in self.items:
                if _item:
                    _items.append(_item.to_dict())
            _dict['items'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TemplatePatchRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "archived_at": obj.get("archived_at"),
            "created_at": obj.get("created_at"),
            "id": obj.get("id"),
            "items": [TemplateItem.from_dict(_item) for _item in obj["items"]] if obj.get("items") is not None else None,
            "label_ids": obj.get("label_ids"),
            "name": obj.get("name"),
            "published_at": obj.get("published_at"),
            "recording_name_format": obj.get("recording_name_format"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


