# coding: utf-8

"""
    Pupil Cloud

    Pupil Cloud API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "pupilcloud"
VERSION = "2.0.0"
PYTHON_REQUIRES = ">=3.7"

REQUIRES = [
    "urllib3 >= 1.25.3, < 2.1.0",
    "python-dateutil",
    "aiohttp >= 3.0.0",
    "aiohttp-retry >= 2.8.3",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="Pupil Cloud API Python Client",
    author="Pupil Labs GmbH",
    author_email="info@pupil-labs.com",
    url="https://github.com/pupil-labs/pupil-cloud-client-python",
    keywords=["OpenAPI", "Pupil Cloud", "API Client", "Python"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    license="MIT",
    long_description_content_type='text/markdown',
    long_description="""\
    This is the Python client for the Pupil Labs Cloud API.
    """,  # noqa: E501
    package_data={"pupilcloud": ["py.typed"]},
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3 :: Only",
    ],
    project_urls={
        "Documentation": "https://github.com/pupil-labs/pupil-cloud-client-python",
        "Source": "https://github.com/pupil-labs/pupil-cloud-client-python",
        "Tracker": "https://github.com/pupil-labs/pupil-cloud-client-python/issues",
    },
)